//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Divisa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Divisa()
        {
            this.MisMonedas = new HashSet<MisMoneda>();
        }
    
        public int DivisaId { get; set; }
        public string Nombre { get; set; }
        public decimal Valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MisMoneda> MisMonedas { get; set; }
    }
}
