//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int HistorialId { get; set; }
        public int UsuarioId { get; set; }
        public string TipoTransaccion { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public decimal Cargo { get; set; }
        public decimal Total { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
