//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet.UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wallet4Entities : DbContext
    {
        public Wallet4Entities()
            : base("name=Wallet4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Divisa> Divisas { get; set; }
        public virtual DbSet<Historial> Historials { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<MisMoneda> MisMonedas { get; set; }
    }
}
